#!/bin/bash


test() {
  docker-compose exec app phpcs /app/test.php
}


help() {
  echo "-----------------------------------------------------------------------"
  echo "                      Available commands                              -"
  echo "-----------------------------------------------------------------------"
  echo "   > test - To Test "
  echo "-----------------------------------------------------------------------"
}

if [ $# -eq 0 ]
  then
    help
fi

$*
