FROM jenkins/jenkins

USER root

RUN apt-get update && apt-get install -y apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
RUN apt-get update && apt-get install -y docker-ce
RUN usermod -aG docker jenkins
# RUN jenkins restart

# USER jenkins
