FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive

RUN apt -y update

# Download Java
RUN apt -y install default-jdk

# Download SonarQube
RUN apt install -y unzip wget
RUN wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
RUN unzip sonarqube-7.3.zip -d /opt
RUN rm sonarqube-7.3.zip

ADD ./SonarQube/conf/sonar.properties /opt/sonarqube-7.3/conf/
ADD ./SonarQube/systemd/sonar.service /etc/systemd/system/
RUN /opt/sonarqube-7.3/bin/linux-x86-64/sonar.sh start



CMD tail -f /dev/null
